package cookie

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"sync"

	"github.com/kumneger0/yt-tracks/internal/config"
)

var (
	cachedCookieHeader string
	cookieHeaderOnce   sync.Once
	cookieHeaderMu     sync.RWMutex
)

const netscapeCookieHeader = "# Netscape HTTP Cookie File"

func ResetCookieHeaderCache() {
	cookieHeaderMu.Lock()
	defer cookieHeaderMu.Unlock()
	cachedCookieHeader = ""
	cookieHeaderOnce = sync.Once{}
}

func ConvertToNetscapeCookies(cookieText string) string {
	cookieText = strings.TrimSpace(cookieText)
	if cookieText == "" {
		return netscapeCookieHeader + "\n"
	}
	if isNetscapeCookieFile(cookieText) {
		return cookieText
	}

	if hasTabSeparatedCookieLines(cookieText) {
		return fmt.Sprintf("%s\n\n%s", netspaceFileHeader(), cookieText)
	}

	if lines, ok := convertJSONCookieListToNetscape(cookieText); ok {
		return strings.Join(lines, "\n")
	}

	if header, ok := extractCookieHeaderFromJSON(cookieText); ok {
		return buildNetscapeHeaderFromCookieText(header)
	}

	return buildNetscapeHeaderFromCookieText(cookieText)
}

func isNetscapeCookieFile(cookieText string) bool {
	return strings.HasPrefix(cookieText, netscapeCookieHeader) || strings.HasPrefix(cookieText, "# HTTP Cookie File")
}

func hasTabSeparatedCookieLines(cookieText string) bool {
	lines := []string{}
	for l := range strings.SplitSeq(cookieText, "\n") {
		trimmed := strings.TrimSpace(l)
		if trimmed != "" && !strings.HasPrefix(trimmed, "#") {
			lines = append(lines, trimmed)
		}
	}
	if len(lines) == 0 {
		return false
	}
	for _, line := range lines {
		if len(strings.Split(line, "\t")) < 7 {
			return false
		}
	}
	return true
}

func netspaceFileHeader() string {
	return netscapeCookieHeader
}

func extractCookieHeaderFromJSON(cookieText string) (string, bool) {
	var rawData any
	if err := json.Unmarshal([]byte(cookieText), &rawData); err != nil {
		return "", false
	}

	switch typedValue := rawData.(type) {
	case map[string]any:
		if cookieHeader, ok := extractCookieHeaderFromMap(typedValue); ok {
			return cookieHeader, true
		}
	case []any:
		if lines, ok := convertCookieListToNetscape(typedValue); ok {
			return strings.Join(lines, "\n"), true
		}
	}

	return "", false
}

func extractCookieHeaderFromMap(payload map[string]any) (string, bool) {
	if c, ok := payload["Cookie"].(string); ok && c != "" {
		return c, true
	}
	if c, ok := payload["cookie"].(string); ok && c != "" {
		return c, true
	}

	headersObj, ok := payload["headers"].(map[string]any)
	if !ok {
		return "", false
	}
	if c, ok := headersObj["Cookie"].(string); ok && c != "" {
		return c, true
	}
	if c, ok := headersObj["cookie"].(string); ok && c != "" {
		return c, true
	}
	return "", false
}

func convertJSONCookieListToNetscape(cookieText string) ([]string, bool) {
	var rawData any
	if err := json.Unmarshal([]byte(cookieText), &rawData); err != nil {
		return nil, false
	}
	if typedValue, ok := rawData.([]any); ok {
		return convertCookieListToNetscape(typedValue)
	}
	return nil, false
}

func convertCookieListToNetscape(items []any) ([]string, bool) {
	netscapeLines := []string{
		netscapeCookieHeader,
		"# https://curl.se/docs/http-cookies.html",
		"# This file was generated by clispot",
		"",
	}
	for _, item := range items {
		itemMap, ok := item.(map[string]any)
		if !ok {
			continue
		}
		cookieEntry, ok := buildCookieEntry(itemMap)
		if !ok {
			continue
		}
		netscapeLines = append(netscapeLines, cookieEntry)
	}
	if len(netscapeLines) == 4 {
		return nil, false
	}
	return netscapeLines, true
}

func buildCookieEntry(itemMap map[string]any) (string, bool) {
	name := cookieStringValue(itemMap["name"])
	val := cookieStringValue(itemMap["value"])
	if name == "" || val == "" {
		return "", false
	}

	domain := cookieStringValue(itemMap["domain"])
	if domain == "" {
		domain = ".youtube.com"
	}
	if httpOnly, ok := itemMap["httpOnly"].(bool); ok && httpOnly && !strings.HasPrefix(domain, "#HttpOnly_") {
		domain = "#HttpOnly_" + domain
	}
	flag := "FALSE"
	if strings.HasPrefix(domain, ".") || strings.HasPrefix(domain, "#HttpOnly_.") {
		flag = "TRUE"
	}

	path := cookieStringValue(itemMap["path"])
	if path == "" {
		path = "/"
	}

	secure := "TRUE"
	if sec, ok := itemMap["secure"].(bool); ok && !sec {
		secure = "FALSE"
	}

	expiry := expiryValue(itemMap)
	return fmt.Sprintf("%s\t%s\t%s\t%s\t%d\t%s\t%s", domain, flag, path, secure, expiry, name, val), true
}

func cookieStringValue(value any) string {
	if value == nil {
		return ""
	}
	return fmt.Sprintf("%v", value)
}

func expiryValue(itemMap map[string]any) int64 {
	for _, key := range []string{"expirationDate", "expiry", "expires"} {
		if expVal, ok := itemMap[key]; ok && expVal != nil {
			if expInt, err := strconv.ParseInt(fmt.Sprintf("%.0f", expVal), 10, 64); err == nil {
				return expInt
			}
		}
	}
	return 2147483647
}

func buildNetscapeHeaderFromCookieText(cookieHeaderStr string) string {
	netscapeLines := []string{
		netscapeCookieHeader,
		"# https://curl.se/docs/http-cookies.html",
		"# This file was generated by clispot",
		"",
	}
	reHeader := regexp.MustCompile(`(?i)^(cookie|Cookie):\s*`)
	rawStr := reHeader.ReplaceAllString(strings.TrimSpace(cookieHeaderStr), "")
	reSplit := regexp.MustCompile(`[;\r\n]+`)
	items := reSplit.Split(rawStr, -1)
	for _, itemStr := range items {
		cleanItem := strings.TrimSpace(itemStr)
		if cleanItem == "" || !strings.Contains(cleanItem, "=") {
			continue
		}
		parts := strings.SplitN(cleanItem, "=", 2)
		cookieName := strings.TrimSpace(parts[0])
		cookieVal := strings.TrimSpace(parts[1])
		if cookieName == "" {
			continue
		}
		netscapeLines = append(netscapeLines, fmt.Sprintf(".youtube.com\tTRUE\t/\tTRUE\t2147483647\t%s\t%s", cookieName, cookieVal))
	}
	return strings.Join(netscapeLines, "\n")
}

func GetCookieFilePath() string {
	configDir := config.GetConfigDir(runtime.GOOS)
	return filepath.Join(configDir, "cookie.txt")
}

func SaveCookieFile(cookieText string) (string, error) {
	ResetCookieHeaderCache()
	cookiePath := GetCookieFilePath()
	netscapeContent := ConvertToNetscapeCookies(cookieText)

	if err := os.WriteFile(cookiePath, []byte(netscapeContent), 0600); err != nil {
		slog.Error("failed to write cookie.txt", "err", err)
		return "", err
	}

	if err := os.Chmod(cookiePath, 0600); err != nil {
		slog.Error("failed to set permissions on cookie.txt", "err", err)
	}

	return cookiePath, nil
}

func EnsureCookieFile() string {
	cookiePath := GetCookieFilePath()
	configDir := config.GetConfigDir(runtime.GOOS)
	browserPath := filepath.Join(configDir, "browser.json")

	browserData, err := os.ReadFile(browserPath)
	if err != nil || len(browserData) == 0 {
		if fi, err := os.Stat(cookiePath); err == nil && fi.Size() > 0 {
			return cookiePath
		}
		return ""
	}

	path, err := SaveCookieFile(string(browserData))
	if err != nil {
		return ""
	}
	return path
}

func GetCookieHeader() string {
	cookieHeaderMu.RLock()
	header := cachedCookieHeader
	cookieHeaderMu.RUnlock()
	if header != "" {
		return header
	}

	cookieHeaderMu.Lock()
	defer cookieHeaderMu.Unlock()

	cookieHeaderOnce.Do(func() {
		configDir := config.GetConfigDir(runtime.GOOS)
		browserPath := filepath.Join(configDir, "browser.json")
		if browserData, err := os.ReadFile(browserPath); err == nil && len(browserData) > 0 {
			var rawData map[string]any
			if err := json.Unmarshal(browserData, &rawData); err == nil {
				if c, ok := rawData["Cookie"].(string); ok && c != "" {
					cachedCookieHeader = c
					return
				}
				if c, ok := rawData["cookie"].(string); ok && c != "" {
					cachedCookieHeader = c
					return
				}
				if headersObj, ok := rawData["headers"].(map[string]any); ok {
					if c, ok := headersObj["Cookie"].(string); ok && c != "" {
						cachedCookieHeader = c
						return
					}
					if c, ok := headersObj["cookie"].(string); ok && c != "" {
						cachedCookieHeader = c
						return
					}
				}
			}
		}
	})
	return cachedCookieHeader
}
